# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="LGPL-3.0"
#issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId="professions" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
# ${file.jarVersion} will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
# see the associated build.gradle script for how to populate this completely automatically during a build
version="0.3.7" #mandatory ugh
displayName="Professions" #mandatory
#updateJSONURL="http://myurl.me/" #optional
displayURL="https://discord.gg/GZjtAn3F6W" #optional
#logoFile="croptopia-forge.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="Thonk" #optional
description='''
Professions that earn you configurable rewards.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.professions]] #optional
   modId="forge" #mandatory
   mandatory=true #mandatory
   versionRange="[40,)" #mandatory
   ordering="NONE"
   side="SERVER"
# Here's another dependency
[[dependencies.professions]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.18.2,)"
   ordering="NONE"
   side="SERVER"
[[dependencies.professions]]
modId="octo_economy_api"
mandatory=true
versionRange="[1.0.0,2.0.0)"
ordering="BEFORE"
side="BOTH"
