# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.
# Project
version=2.3.4
group=com.epherical
java_version=25
# Common
minecraft_version=26.1.2
mod_name=Professions
mod_author=iThonk
mod_id=professions
license=LGPL-3.0
credits=
description=Professions 2 - Leveling For you
minecraft_version_range=[26.1.2, 26.2)
neo_form_version=26.1.2-1


# Fabric
fabric_version=0.145.4+26.1.2
fabric_loader_version=0.18.6

# NeoForge
neoforge_version=26.1.2.45-beta
neoforge_loader_version_range=[4,)
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
